name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Changing to project directory
        run: cd controller-fix

      - name: Installing NPM packages
        run: npm ci
        working-directory: ./controller-fix

      - name: Building project
        run: npm run build
        working-directory: ./controller-fix

      - name: Running tests
        run: npm run test
        working-directory: ./controller-fix

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./controller-fix/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./controller-fix/build

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./controller-fix/build
